"use client";

import {useEffect,useState}from"react";
import {AppShell}from"./app-shell.js";
import {Button,FeedbackSurface,Skeleton,StatePanel,Status,TextField,WrittenSolutionField}from"./ui.js";
import {idempotencyKey,requestJson}from"../lib/api-client.js";

type Outcome="CORRECT"|"PARTIALLY_CORRECT"|"INCORRECT"|"UNCERTAIN";
type View={sessionId:string;task:{prompt:{body:string};input:"text"|"written_solution"|"unavailable"};state:{stage:"working"|"verified";outcome?:Outcome};canReveal:boolean};
type Reveal={title:string;explanation:{body:string}};
type RevealResponse={reveal:Reveal};

export function TransferWorkspace({sessionId}:{sessionId:string}){
  const draftKey=`thinkai:transfer:${sessionId}:draft`;
  const [view,setView]=useState<View>(); const [answer,setAnswer]=useState(""); const [reasoning,setReasoning]=useState(""); const [error,setError]=useState<string>(); const [noFresh,setNoFresh]=useState(false); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [reveal,setReveal]=useState<Reveal>(); const [revealing,setRevealing]=useState(false);
  const load=async()=>{setLoading(true);setError(undefined);try{setView(await requestJson<View>(`/api/v1/transfers/${sessionId}`));}catch(cause){setError(cause instanceof Error?cause.message:"Không thể mở phần vận dụng.");}finally{setLoading(false);}};
  useEffect(()=>{const draft=sessionStorage.getItem(draftKey);if(draft){try{const value=JSON.parse(draft) as {answer?:string;reasoning?:string};setAnswer(value.answer??"");setReasoning(value.reasoning??"");}catch{sessionStorage.removeItem(draftKey);}}void load();},[sessionId]);
  useEffect(()=>{if(!view?.state.outcome)sessionStorage.setItem(draftKey,JSON.stringify({answer,reasoning}));},[answer,reasoning,draftKey,view?.state.outcome]);
  const submit=async()=>{setSubmitting(true);setError(undefined);try{await requestJson(`/api/v1/transfers/${sessionId}/submissions`,{method:"POST",body:{answer:view?.task.input==="written_solution"?reasoning:answer},idempotencyKey:idempotencyKey()});sessionStorage.removeItem(draftKey);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Không thể gửi bài. Bài làm vẫn được giữ lại.");}finally{setSubmitting(false);}};
  const retry=async()=>{setSubmitting(true);setError(undefined);setNoFresh(false);try{const next=await requestJson<{nextAction:string;sessionId?:string}>(`/api/v1/transfers/${sessionId}/retry`,{method:"POST",body:{},idempotencyKey:idempotencyKey()});if(next.sessionId)location.assign(`/transfer/${next.sessionId}`);else if(next.nextAction==="NO_FRESH_TRANSFER_AVAILABLE")setNoFresh(true);else setError("Chưa thể chọn tình huống mới để kiểm tra độc lập.");}catch(cause){setError(cause instanceof Error?cause.message:"Chưa thể chọn tình huống mới.");}finally{setSubmitting(false);}};
  const openReveal=async()=>{setRevealing(true);setError(undefined);try{const result=await requestJson<RevealResponse>(`/api/v1/transfers/${sessionId}/connection/reveal`,{method:"POST",body:{},idempotencyKey:idempotencyKey()});if(!result.reveal?.title||!result.reveal.explanation?.body)throw new Error("Nội dung liên hệ chưa hợp lệ.");setReveal(result.reveal);}catch(cause){setError(cause instanceof Error?cause.message:"Chưa thể mở liên hệ.");}finally{setRevealing(false);}};const openReceipt=async()=>{try{const result=await requestJson<{receipt:{id:string}}>(`/api/v1/transfers/${sessionId}/receipt`,{method:"POST",body:{},idempotencyKey:idempotencyKey()});location.assign(`/receipts/${result.receipt.id}`);}catch(cause){setError(cause instanceof Error?cause.message:"Chưa thể tạo xác nhận.");}};
  const outcome=view?.state.outcome;
  return <AppShell active="learn" context="Thử vận dụng"><main className="page-shell" id="main-content"><header className="practice-header"><div><div className="page-eyebrow">THỬ VẬN DỤNG</div><h1 className="page-title">Tự áp dụng trong tình huống mới</h1><p className="page-description">Tự làm bài này. Không có gợi ý hay hỗ trợ trong phần kiểm tra độc lập.</p></div></header><div className="page-body">{loading?<div className="learner-loading"><Skeleton title/><Skeleton/></div>:error&&!view?<StatePanel tone="error" title="Không thể mở bài" actions={<Button onClick={()=>void load()}>Thử lại</Button>}>{error}</StatePanel>:view?<section className="transfer-workspace"><div className="section-label">ĐỀ BÀI</div><div className="practice-prompt">{view.task.prompt.body}</div>{error?<StatePanel tone="error" title="Thao tác chưa hoàn tất" actions={<Button tone="quiet" onClick={()=>void load()}>Tải lại trạng thái</Button>}>{error}</StatePanel>:null}{noFresh?<StatePanel tone="uncertain" title="Chưa có tình huống mới phù hợp">Không còn bài kiểm tra độc lập chưa từng xuất hiện. Hãy quay lại phần học để ôn thêm.</StatePanel>:null}{!outcome?view.task.input==="unavailable"?<StatePanel tone="uncertain" title="Dạng bài này chưa sẵn sàng">Không thể mở bài vận dụng này. Hãy quay lại phần học.</StatePanel>:<div className="practice-form">{view.task.input==="text"?<TextField id="transfer-answer" label="Đáp án của bạn" value={answer} onChange={event=>setAnswer(event.target.value)} />:null}{view.task.input==="written_solution"?<WrittenSolutionField id="transfer-reasoning" label="Cách bạn lập luận" value={reasoning} onChange={event=>setReasoning(event.target.value)} placeholder="Viết các bước bạn đã dùng…"/>:null}<Button loading={submitting} disabled={view.task.input==="text"?!answer.trim():!reasoning.trim()} onClick={()=>void submit()}>Gửi bài làm</Button></div>:<section className="practice-result" aria-live="polite"><Status tone={outcome==="CORRECT"?"success":outcome==="UNCERTAIN"?"uncertain":"partial"}>{outcome==="CORRECT"?"Đã xác minh":outcome==="UNCERTAIN"?"Chưa thể xác nhận":"Chưa đạt"}</Status><h2>{outcome==="CORRECT"?"Bạn đã áp dụng được kiến thức một cách độc lập.":outcome==="UNCERTAIN"?"Kết quả chưa đủ để xác nhận." :"Lần thử này chưa xác minh được cách áp dụng độc lập."}</h2>{view.canReveal?<><Button loading={revealing} onClick={()=>void openReveal()}>Xem mối liên hệ</Button>{reveal?<><FeedbackSurface title={reveal.title}>{reveal.explanation.body}</FeedbackSurface><Button tone="quiet" onClick={()=>void openReceipt()}>Xem xác nhận kỹ năng</Button></>:null}</>:<StatePanel tone={outcome==="UNCERTAIN"?"uncertain":"partial"} title="Chưa mở mối liên hệ" actions={!noFresh?<Button loading={submitting} onClick={()=>void retry()}>Thử tình huống mới</Button>:undefined}>Kết quả kiểm tra độc lập chưa được xác minh. Nếu còn bài phù hợp, hệ thống sẽ chọn một tình huống mới.</StatePanel>}</section>}</section>:null}</div></main></AppShell>;
}
