"use client";
import {useEffect,useState} from "react";
type Skill={microSkillId?:string;microSkillRevisionId?:string;displayOrder?:number;skillId?:string};
const key=()=>crypto.randomUUID();
export default function ThinkAI(){const [skills,setSkills]=useState<Skill[]>([]);const [practice,setPractice]=useState("");const [transfer,setTransfer]=useState("");const [answer,setAnswer]=useState("");const [message,setMessage]=useState("Loading published learning path…");const api=async(path:string,body:unknown)=>fetch(path,{method:"POST",credentials:"include",headers:{"content-type":"application/json","Idempotency-Key":key()},body:JSON.stringify(body)});
const start=async(s:Skill)=>{setMessage("Starting server-bound Practice…");const r=await api("/api/v1/practice/start",{microSkillRevisionId:s.microSkillRevisionId});const x=await r.json();if(r.ok){setPractice(x.sessionId);setMessage("Practice pair bound by server.");}else setMessage(x.error?.message??"Practice is unavailable.");};
const submitPractice=async()=>{const r=await api(`/api/v1/challenges/${practice}/submissions`,{answer});const x=await r.json();if(r.ok&&x.challenge?.stage==="solved")setMessage("Practice verified. Independent Transfer is available.");else setMessage(x.error?.message??"Practice submitted; continue working if needed.");};
const startTransfer=async()=>{const id=`transfer_${crypto.randomUUID().replaceAll("-","")}`;const r=await api(`/api/v1/challenges/${practice}/transfer/start`,{sessionId:id});const x=await r.json();if(r.ok){setTransfer(x.transfer.sessionId);setMessage("Independent Transfer started. No Practice help is available here.");}else setMessage(x.error?.message??"Transfer is unavailable.");};
const submitTransfer=async()=>{const r=await api(`/api/v1/transfers/${transfer}/submissions`,{answer});const x=await r.json();if(r.ok&&x.transfer?.stage==="verified")setMessage("Transfer verified. You may reveal the reviewed connection.");else setMessage(x.error?.message??"Transfer recorded without verification.");};
const reveal=async()=>{const r=await api(`/api/v1/transfers/${transfer}/connection/reveal`,{});const x=await r.json();setMessage(r.ok?x.reveal?.explanation?.body??"Connection revealed.":x.error?.message??"Reveal unavailable.");};const receipt=async()=>{const r=await api("/api/v1/receipts/issue",{practiceSessionId:practice,transferSessionId:transfer});const x=await r.json();setMessage(r.ok?`Capability Receipt issued: ${x.receipt?.id}`:x.error?.message??"Receipt unavailable.");};const progress=async()=>{const r=await fetch("/api/v1/progress",{credentials:"include"});setMessage(r.ok?"Progress history loaded from persisted evidence.":"Progress unavailable.");};
useEffect(()=>{fetch("/api/v1/skills",{credentials:"include"}).then(r=>r.json()).then(x=>{setSkills(x.active??[]);setMessage(x.active?.length?"Choose a published micro-skill.":"No published Practice is available.");}).catch(()=>setMessage("Published content is unavailable."));},[]);
return <main><h1>ThinkAI</h1><p aria-live="polite">{message}</p><ul>{skills.map((s,i)=><li key={s.microSkillRevisionId??s.skillId??i}>{s.microSkillId??s.skillId} <button onClick={()=>start(s)}>Start Practice</button></li>)}</ul>{practice&&<section><h2>Practice</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain your working; LaTeX is not required."/><button onClick={submitPractice}>Submit Practice</button><button onClick={startTransfer}>Start Independent Transfer</button></section>}{transfer&&<section><h2>Independent Transfer</h2><p>No hints, Practice feedback, transcript, or AI context are provided.</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Enter your independent answer."/><button onClick={submitTransfer}>Submit Transfer</button><button onClick={reveal}>Reveal connection after verification</button><button onClick={receipt}>Issue Capability Receipt after verification</button></section>}<button onClick={progress}>Load Progress & History</button><p>Pair/task/version, scoring, reveal and receipt eligibility are server-authoritative.</p></main>}
