import { createHash } from "node:crypto";
import type { ReviewedContentRepository } from "../content/repository.js";
import type { ReviewedPairSnapshot } from "../content/snapshot.js";
import { challengeSessionId, evidenceEventId, transferSessionId, type ActorId, type ChallengeSessionId, type SkillId, type TaskFamilyId, type TaskId, type TransferSessionId } from "../domain/ids.js";
import { EVIDENCE_EVENT_SCHEMA_VERSION } from "../domain/policies.js";
import type { EvidenceEvent } from "../evidence/schema.js";
import type { AppendEvidenceCommand, SessionSnapshot } from "../persistence/index.js";
import type { ScoreResult, ScoringService, SubmittedAnswer } from "../scoring/service.js";

type Stage = "working" | "verified";
type Op = { fingerprint: string; stage: Stage; attempts: number; score?: ScoreResult };
export interface ConnectionReveal { readonly title:string; readonly sharedRelation:string; readonly explanation:{readonly format:string;readonly body:string}; readonly practiceHighlights:readonly string[]; readonly transferHighlights:readonly string[]; readonly pairVersion:string; }
type State = { version: 1; actorId: ActorId; practiceSessionId: ChallengeSessionId; pairId: string; pairVersion: string; skillId: SkillId; taskId: TaskId; taskVersion: string; familyId: TaskFamilyId; snapshotKey: string; stage: Stage; attempts: number; lastScore?: ScoreResult; reveal?:ConnectionReveal; operations: Record<string, Op> };
export interface TransferPersistence { appendCommand(command: AppendEvidenceCommand): Promise<unknown>; find(id: string): Promise<SessionSnapshot | undefined>; findContent(key: string): Promise<ReviewedPairSnapshot | undefined>; }
export interface TransferView { readonly sessionId: TransferSessionId; readonly skillId: SkillId; readonly taskId: TaskId; readonly taskVersion: string; readonly taskFamilyId: TaskFamilyId; readonly stage: Stage; readonly attempts: number; readonly connectionRevealAvailable: boolean; readonly lastScore?: ScoreResult; }
export interface TransferSafeContext { readonly transferSessionId: TransferSessionId; readonly skillId: SkillId; readonly transferTaskId: TaskId; readonly transferTaskVersion: string; readonly transferTaskFamilyId: TaskFamilyId; readonly stage: Stage; }
export class TransferError extends Error { constructor(public readonly code: "PRACTICE_NOT_ELIGIBLE"|"SESSION_NOT_FOUND"|"ACTOR_MISMATCH"|"INVALID_TRANSITION"|"CONTENT_VERSION_DRIFT"|"IDEMPOTENCY_CONFLICT", message: string) { super(message); this.name="TransferError"; } }
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
const eventId=(id:string,key:string,n:number)=>evidenceEventId(`event_${hash(`${id}|${key}|${n}`).slice(0,32)}`);
const validScore=(x:unknown): x is ScoreResult => !!x && typeof x==="object" && ["correct","incorrect","invalid"].includes(String((x as ScoreResult).outcome)) && typeof (x as ScoreResult).scorerVersion==="string";
function parse(snapshot: SessionSnapshot): State { const s=snapshot.state as Record<string,unknown>; if(snapshot.kind!=="transfer"||s.version!==1||!(["working","verified"] as string[]).includes(String(s.stage))||typeof s.actorId!=="string"||typeof s.practiceSessionId!=="string"||typeof s.pairId!=="string"||typeof s.pairVersion!=="string"||typeof s.skillId!=="string"||typeof s.taskId!=="string"||typeof s.taskVersion!=="string"||typeof s.familyId!=="string"||typeof s.snapshotKey!=="string"||!Number.isInteger(s.attempts)||!s.operations||typeof s.operations!=="object") throw new TransferError("CONTENT_VERSION_DRIFT","Malformed transfer snapshot."); const operations:Record<string,Op>={}; for(const [k,v] of Object.entries(s.operations as Record<string,unknown>)){if(!v||typeof v!=="object") throw new TransferError("CONTENT_VERSION_DRIFT","Malformed idempotency state."); const o=v as Record<string,unknown>; if(typeof o.fingerprint!=="string"||!(["working","verified"] as string[]).includes(String(o.stage))||!Number.isInteger(o.attempts)||(o.score!==undefined&&!validScore(o.score))) throw new TransferError("CONTENT_VERSION_DRIFT","Malformed idempotency state."); operations[k]={fingerprint:o.fingerprint,stage:o.stage as Stage,attempts:o.attempts as number,...(validScore(o.score)?{score:o.score}:{})};} const reveal=s.reveal as ConnectionReveal|undefined; return {version:1,actorId:s.actorId as ActorId,practiceSessionId:challengeSessionId(s.practiceSessionId),pairId:s.pairId,pairVersion:s.pairVersion,skillId:s.skillId as SkillId,taskId:s.taskId as TaskId,taskVersion:s.taskVersion as string,familyId:s.familyId as TaskFamilyId,snapshotKey:s.snapshotKey as string,stage:s.stage as Stage,attempts:s.attempts as number,...(validScore(s.lastScore)?{lastScore:s.lastScore}:{}),...(reveal&&typeof reveal.sharedRelation==="string"?{reveal}:{}),operations}; }
export class TransferService {
  constructor(private readonly content:ReviewedContentRepository,private readonly persistence:TransferPersistence,private readonly scoring:ScoringService,private readonly now=()=>new Date()){}
  async start(input:{sessionId:TransferSessionId;practiceSessionId:ChallengeSessionId;actorId:ActorId;idempotencyKey:string;actorSessionId?:string}):Promise<{replayed:boolean;transfer:TransferView}>{
    const existing=await this.persistence.find(input.sessionId); const fp=JSON.stringify({a:"start",practice:input.practiceSessionId,actor:input.actorId}); if(existing)return this.replay(input.sessionId,input.actorId,parse(existing),input.idempotencyKey,fp);
    const practice=await this.persistence.find(input.practiceSessionId); if(!practice)throw new TransferError("SESSION_NOT_FOUND","Practice session was not found."); const ps=practice.state as Record<string,unknown>; if(practice.kind!=="challenge"||ps.stage!=="solved"||ps.actorId!==input.actorId||typeof ps.pairId!=="string")throw new TransferError("PRACTICE_NOT_ELIGIBLE","Only the learner's solved practice session can start transfer.");
    const pair=this.content.getReviewedPair(ps.pairId as never); const task=this.content.getTask(pair.transferTaskId); if(pair.version!==ps.pairVersion||pair.review.status!=="approved"||task.review.status!=="approved"||task.role!=="transfer")throw new TransferError("CONTENT_VERSION_DRIFT","Linked reviewed transfer content is unavailable."); const snap=this.content.createPairSnapshot(pair.id); const state:State={version:1,actorId:input.actorId,practiceSessionId:input.practiceSessionId,pairId:pair.id,pairVersion:pair.version,skillId:pair.skillId,taskId:task.id,taskVersion:task.version,familyId:task.familyId,snapshotKey:snap.integrityKey,stage:"working",attempts:0,operations:{}}; const next=this.withOp(state,input.idempotencyKey,fp); await this.persist(input.sessionId,input.idempotencyKey,next,[this.event(input.sessionId,input.idempotencyKey,0,next,task,"transfer_started",{pairId:pair.id,pairVersion:pair.version,transferTaskId:task.id,transferTaskVersion:task.version,contentIntegrityKey:snap.integrityKey})],snap,input.actorSessionId); return {replayed:false,transfer:this.view(input.sessionId,next)};
  }
  async submit(input:{sessionId:TransferSessionId;actorId:ActorId;answer:SubmittedAnswer;idempotencyKey:string;actorSessionId?:string}):Promise<{replayed:boolean;transfer:TransferView;score?:ScoreResult}>{const loaded=await this.load(input.sessionId,input.actorId);const fp=JSON.stringify({a:"submit",answer:input.answer});const replay=this.replayMaybe(input.sessionId,loaded.state,input.idempotencyKey,fp);if(replay)return replay;if(loaded.state.stage!=="working")throw new TransferError("INVALID_TRANSITION","This Transfer Quest is already verified.");const score=this.scoring.score(loaded.task,input.answer);const state:State={...loaded.state,stage:score.outcome==="correct"?"verified":"working",attempts:loaded.state.attempts+1,lastScore:score};const next=this.withOp(state,input.idempotencyKey,fp);await this.persist(input.sessionId,input.idempotencyKey,next,[this.event(input.sessionId,input.idempotencyKey,0,next,loaded.task,"transfer_submitted",{answerKind:typeof input.answer==="string"?"text":input.answer.kind,ordinal:next.attempts}),this.event(input.sessionId,input.idempotencyKey,1,next,loaded.task,"transfer_scored",{outcome:score.outcome,answerSpecVersion:score.answerSpecVersion,...(score.reasonCode?{reasonCode:score.reasonCode}:{})},score.scorerVersion)],undefined,input.actorSessionId);return {replayed:false,transfer:this.view(input.sessionId,next),score};}
  async resume(id:TransferSessionId,actor:ActorId){const l=await this.load(id,actor);return this.view(id,l.state)}
  async revealConnection(input:{sessionId:TransferSessionId;actorId:ActorId;idempotencyKey:string;actorSessionId?:string}):Promise<{replayed:boolean;reveal:ConnectionReveal}>{const loaded=await this.load(input.sessionId,input.actorId);if(loaded.state.reveal)return {replayed:true,reveal:loaded.state.reveal};if(loaded.state.stage!=="verified")throw new TransferError("INVALID_TRANSITION","Connection is available only after a verified transfer result.");const pair=this.content.getReviewedPair(loaded.snapshot.pair.id as never);if(pair.version!==loaded.snapshot.pair.version||pair.review.status!=="approved")throw new TransferError("CONTENT_VERSION_DRIFT","Reviewed relation mapping drifted.");const reveal:ConnectionReveal=Object.freeze({...pair.relationMapping,pairVersion:pair.version,practiceHighlights:Object.freeze([...pair.relationMapping.practiceHighlights]),transferHighlights:Object.freeze([...pair.relationMapping.transferHighlights])});const state:State={...loaded.state,reveal};await this.persist(input.sessionId,input.idempotencyKey,state,[this.event(input.sessionId,input.idempotencyKey,0,state,loaded.task,"connection_revealed",{pairId:pair.id,pairVersion:pair.version,relationMappingVersion:pair.version})],undefined,input.actorSessionId);return {replayed:false,reveal};}
  buildAiSafeContext(view:TransferView):TransferSafeContext{return Object.freeze({transferSessionId:view.sessionId,skillId:view.skillId,transferTaskId:view.taskId,transferTaskVersion:view.taskVersion,transferTaskFamilyId:view.taskFamilyId,stage:view.stage});}
  private async load(id:TransferSessionId,actor:ActorId){const ss=await this.persistence.find(id);if(!ss)throw new TransferError("SESSION_NOT_FOUND","Transfer session was not found.");const state=parse(ss);if(state.actorId!==actor)throw new TransferError("ACTOR_MISMATCH","Transfer belongs to another learner.");const snap=await this.persistence.findContent(state.snapshotKey);if(!snap||snap.pair.id!==state.pairId||snap.pair.version!==state.pairVersion)throw new TransferError("CONTENT_VERSION_DRIFT","Transfer snapshot pair drifted.");try{this.content.assertSnapshotIntegrity(snap);}catch{throw new TransferError("CONTENT_VERSION_DRIFT","Reviewed content drifted from the transfer snapshot.");}const task=this.content.getTask(state.taskId);if(task.role!=="transfer"||task.version!==state.taskVersion||task.familyId!==state.familyId||task.review.status!=="approved")throw new TransferError("CONTENT_VERSION_DRIFT","Transfer task drifted.");return {state,task,snapshot:snap};}
  private replay(id:TransferSessionId,actor:ActorId,state:State,key:string,fp:string){if(state.actorId!==actor)throw new TransferError("ACTOR_MISMATCH","Transfer belongs to another learner.");const r=this.replayMaybe(id,state,key,fp);if(!r)throw new TransferError("INVALID_TRANSITION","Transfer session already exists.");return r;}
  private replayMaybe(id:TransferSessionId,state:State,key:string,fp:string){const op=state.operations[key];if(!op)return undefined;if(op.fingerprint!==fp)throw new TransferError("IDEMPOTENCY_CONFLICT","Idempotency key was reused.");const replayed:State={...state,stage:op.stage,attempts:op.attempts,...(op.score?{lastScore:op.score}:{})};return {replayed:true as const,transfer:this.view(id,replayed),...(op.score?{score:op.score}:{})};}
  private withOp(state:State,key:string,fp:string):State{return {...state,operations:{...state.operations,[key]:{fingerprint:fp,stage:state.stage,attempts:state.attempts,...(state.lastScore?{score:state.lastScore}:{})}}};}
  private view(id:TransferSessionId,s:State):TransferView{return Object.freeze({sessionId:id,skillId:s.skillId,taskId:s.taskId,taskVersion:s.taskVersion,taskFamilyId:s.familyId,stage:s.stage,attempts:s.attempts,connectionRevealAvailable:s.stage==="verified",...(s.lastScore?{lastScore:s.lastScore}:{})});}
  private event(id:TransferSessionId,key:string,n:number,s:State,task:{id:TaskId;version:string;familyId:TaskFamilyId},type:EvidenceEvent["type"],payload:Record<string,unknown>,scorerVersion?:string):EvidenceEvent{return {id:eventId(id,key,n),type,actorId:s.actorId,correlationId:id,transferSessionId:id,skillId:s.skillId,taskId:task.id,taskVersion:task.version,taskFamilyId:task.familyId,occurredAt:this.now().toISOString(),schemaVersion:EVIDENCE_EVENT_SCHEMA_VERSION,policyVersion:"transfer-lifecycle-v1",...(scorerVersion?{scorerVersion}:{}),provenance:"live",payload};}
  private async persist(id:TransferSessionId,key:string,state:State,events:EvidenceEvent[],snap?:ReviewedPairSnapshot,actorSessionId?:string){await this.persistence.appendCommand({events,idempotencyKey:`transfer:${id}:${key}`,...(snap?{contentSnapshot:snap}:{}),...(actorSessionId?{actorSessionId}:{}),session:{sessionId:id,kind:"transfer",contentIntegrityKey:state.snapshotKey,state:state as unknown as Record<string,unknown>}});}
}
