/** Framework-free, task-oriented transport adapter. It deliberately owns no learning policy. */
export interface ApiRequest { method:string; path:string; actorId?:string; headers?:Record<string,string|undefined>; body?:unknown }
export interface ApiResponse { status:number; body:unknown }
export interface ApiServices { home(a:string):Promise<unknown>; progress(a:string):Promise<unknown>; audit(a:string,id:string):Promise<unknown>; practice:any; transfer:any; receipts:any }
const err=(code:string,status:number,message:string):ApiResponse=>({status,body:{error:{code,message}}});
const key=(r:ApiRequest)=>r.headers?.["Idempotency-Key"]??r.headers?.["idempotency-key"];
const body=(r:ApiRequest):Record<string,unknown>|undefined=>r.body&&typeof r.body==="object"&&!Array.isArray(r.body)?r.body as Record<string,unknown>:undefined;
const map=(e:unknown):ApiResponse=>{const x=e as {code?:string;message?:string};const c=x.code??"INTERNAL_ERROR";return err(c,c==="ACTOR_MISMATCH"?403:c.includes("NOT_FOUND")||c==="SESSION_NOT_FOUND"?404:c==="INVALID_TRANSITION"||c==="CONTENT_VERSION_DRIFT"||c==="IDEMPOTENCY_CONFLICT"?409:400,x.message??"Request failed.")};
export async function dispatch(s:ApiServices,r:ApiRequest):Promise<ApiResponse>{if(!r.actorId)return err("UNAUTHORIZED",401,"Actor session is required.");const a=r.actorId,p=r.path.split("/").filter(Boolean),b=body(r);try{if(r.method==="GET"&&r.path==="/api/v1/home")return {status:200,body:await s.home(a)};if(r.method==="GET"&&r.path==="/api/v1/progress")return {status:200,body:await s.progress(a)};if(r.method==="GET"&&p[2]==="challenges"&&p[3])return {status:200,body:await s.practice.resume({sessionId:p[3],actorId:a})};if(r.method==="GET"&&p[2]==="transfers"&&p[3])return {status:200,body:await s.transfer.resume(p[3],a)};if(r.method==="GET"&&p[2]==="receipts"&&p[3])return {status:200,body:await s.receipts.get(a,p[3])};if(r.method==="GET"&&p[2]==="audit"&&p[3])return {status:200,body:await s.audit(a,p[3])};if(r.method!=="POST")return err("NOT_FOUND",404,"Route not found.");const k=key(r);if(!k)return err("IDEMPOTENCY_KEY_REQUIRED",400,"Idempotency-Key is required.");if(!b)return err("INVALID_REQUEST",400,"JSON object body is required.");if(r.path==="/api/v1/challenges/start"&&typeof b.sessionId==="string"&&typeof b.pairId==="string")return {status:201,body:await s.practice.start({sessionId:b.sessionId,actorId:a,pairId:b.pairId,idempotencyKey:k})};if(p[2]==="challenges"&&p[3]&&p[4]==="attempts")return {status:200,body:b.kind==="cannot_start"?await s.practice.declareCannotStart({sessionId:p[3],actorId:a,idempotencyKey:k}):await s.practice.recordAttempt({sessionId:p[3],actorId:a,idempotencyKey:k})};if(p[2]==="challenges"&&p[3]&&p[4]==="interventions"&&p[5])return {status:200,body:await s.practice.openReviewedHint({sessionId:p[3],actorId:a,interventionId:p[5],idempotencyKey:k})};if(p[2]==="challenges"&&p[3]&&p[4]==="submissions"&&"answer" in b)return {status:200,body:await s.practice.submit({sessionId:p[3],actorId:a,answer:b.answer,idempotencyKey:k})};if(p[2]==="challenges"&&p[3]&&p[4]==="transfer"&&p[5]==="start"&&typeof b.sessionId==="string")return {status:201,body:await s.transfer.start({sessionId:b.sessionId,practiceSessionId:p[3],actorId:a,idempotencyKey:k})};if(p[2]==="transfers"&&p[3]&&p[4]==="submissions"&&"answer" in b)return {status:200,body:await s.transfer.submit({sessionId:p[3],actorId:a,answer:b.answer,idempotencyKey:k})};if(p[2]==="receipts"&&p[3]==="issue"&&typeof b.practiceSessionId==="string"&&typeof b.transferSessionId==="string")return {status:201,body:await s.receipts.issue({actorId:a,practiceSessionId:b.practiceSessionId,transferSessionId:b.transferSessionId,idempotencyKey:k})};return err("INVALID_REQUEST",400,"Request does not match a supported action.");}catch(e){return map(e)}}
