/** Framework-free transport adapter; learning policy remains in domain services. */
export interface ApiRequest { method:string; path:string; actorId?:string; headers?:Record<string,string|undefined>; body?:unknown }
export interface ApiResponse { status:number; body:unknown }
export interface ApiServices { home(a:string):Promise<unknown>; progress(a:string):Promise<unknown>; audit(a:string,id:string):Promise<unknown>; practice:any; transfer:any; receipts:any }
const response=(status:number,body:unknown):ApiResponse=>({status,body});
const failure=(code:string,status:number,message:string)=>response(status,{error:{code,message}});
const idem=(r:ApiRequest)=>r.headers?.["Idempotency-Key"]??r.headers?.["idempotency-key"];
const object=(x:unknown):Record<string,unknown>|undefined=>x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,unknown>:undefined;
const exception=(e:unknown)=>{const x=e as {code?:string;message?:string};const c=x.code??"INTERNAL_ERROR";return failure(c,c==="ACTOR_MISMATCH"?403:c==="SESSION_NOT_FOUND"?404:["INVALID_TRANSITION","CONTENT_VERSION_DRIFT","IDEMPOTENCY_CONFLICT"].includes(c)?409:400,x.message??"Request failed.")};
export async function dispatch(s:ApiServices,r:ApiRequest):Promise<ApiResponse>{
 if(!r.actorId)return failure("UNAUTHORIZED",401,"Actor session is required."); const actor=r.actorId, parts=r.path.split("/").filter(Boolean), b=object(r.body);
 try { if(r.method==="GET"&&r.path==="/api/v1/home")return response(200,await s.home(actor)); if(r.method==="GET"&&r.path==="/api/v1/progress")return response(200,await s.progress(actor)); if(r.method==="GET"&&parts[2]==="challenges"&&parts[3])return response(200,await s.practice.resume({sessionId:parts[3],actorId:actor})); if(r.method==="GET"&&parts[2]==="transfers"&&parts[3])return response(200,await s.transfer.resume(parts[3],actor)); if(r.method!=="POST")return failure("NOT_FOUND",404,"Route not found."); const key=idem(r);if(!key)return failure("IDEMPOTENCY_KEY_REQUIRED",400,"Idempotency-Key is required.");if(!b)return failure("INVALID_REQUEST",400,"JSON object body is required.");
 if(r.path==="/api/v1/challenges/start"&&typeof b.sessionId==="string"&&typeof b.pairId==="string")return response(201,await s.practice.start({sessionId:b.sessionId,actorId:actor,pairId:b.pairId,idempotencyKey:key}));
 if(parts[2]==="challenges"&&parts[3]&&parts[4]==="attempts")return response(200,b.kind==="cannot_start"?await s.practice.declareCannotStart({sessionId:parts[3],actorId:actor,idempotencyKey:key}):await s.practice.recordAttempt({sessionId:parts[3],actorId:actor,idempotencyKey:key}));
 if(parts[2]==="challenges"&&parts[3]&&parts[4]==="interventions"&&parts[5])return response(200,await s.practice.openReviewedHint({sessionId:parts[3],actorId:actor,interventionId:parts[5],idempotencyKey:key}));
 if(parts[2]==="challenges"&&parts[3]&&parts[4]==="submissions"&&"answer" in b)return response(200,await s.practice.submit({sessionId:parts[3],actorId:actor,answer:b.answer,idempotencyKey:key}));
 if(parts[2]==="challenges"&&parts[3]&&parts[4]==="transfer"&&parts[5]==="start"&&typeof b.sessionId==="string")return response(201,await s.transfer.start({sessionId:b.sessionId,practiceSessionId:parts[3],actorId:actor,idempotencyKey:key}));
 if(parts[2]==="transfers"&&parts[3]&&parts[4]==="submissions"&&"answer" in b)return response(200,await s.transfer.submit({sessionId:parts[3],actorId:actor,answer:b.answer,idempotencyKey:key}));
 if(parts[2]==="transfers"&&parts[3]&&parts[4]==="connection"&&parts[5]==="reveal")return response(200,await s.transfer.revealConnection({sessionId:parts[3],actorId:actor,idempotencyKey:key}));
 if(parts[2]==="receipts"&&parts[3]==="issue"&&typeof b.practiceSessionId==="string"&&typeof b.transferSessionId==="string")return response(201,await s.receipts.issue({actorId:actor,practiceSessionId:b.practiceSessionId,transferSessionId:b.transferSessionId,idempotencyKey:key})); return failure("INVALID_REQUEST",400,"Request does not match a supported action."); } catch(e){return exception(e)} }
