import type { ContentRevisionId } from "../domain/ids.js";
import type { PostgresClient } from "../persistence/index.js";
import { immutableCopy } from "./immutable.js";
import { approveRevision, createDraftRevision, deprecateRevision, editRevision, publishRevision, submitForReview, type ContentRevision } from "./lifecycle.js";
import { assertPublishableContent } from "./publication.js";
import type { ContentAggregate } from "./v11-validator.js";
import { selectFreshTransferPair, selectInitialPair, type ReviewedPairChoice } from "./selection.js";
import type { ActorId, MicroSkillId, TaskId, TaskPairId } from "../domain/ids.js";

type Row = { revision_id: string; lifecycle: ContentRevision<unknown>["lifecycle"]; body: unknown; body_hash: string };
const hydrate = <T>(row: Row): ContentRevision<T> => Object.freeze({ id: row.revision_id as ContentRevisionId, lifecycle: row.lifecycle, body: immutableCopy(row.body as T), bodyHash: row.body_hash });
export class PostgresContentRevisionRepository {
  public constructor(private readonly client: PostgresClient) {}
  public async createDraft<T>(revision: ContentRevision<T>): Promise<ContentRevision<T>> { if (revision.lifecycle !== "DRAFT") throw new Error("Only drafts can be created."); await this.client.query("INSERT INTO content_revisions (revision_id,lifecycle,body,body_hash) VALUES ($1,$2,$3::jsonb,$4)", [revision.id, revision.lifecycle, JSON.stringify(revision.body), revision.bodyHash]); return revision; }
  public async getRevision<T>(id: ContentRevisionId): Promise<ContentRevision<T> | undefined> { const r = await this.client.query<Row>("SELECT revision_id,lifecycle,body,body_hash FROM content_revisions WHERE revision_id=$1", [id]); return r.rows[0] ? hydrate<T>(r.rows[0]) : undefined; }
  private async transition<T>(id: ContentRevisionId, map: (value: ContentRevision<T>) => ContentRevision<T>): Promise<ContentRevision<T>> { return this.client.transaction(async tx => { const r = await tx.query<Row>("SELECT revision_id,lifecycle,body,body_hash FROM content_revisions WHERE revision_id=$1 FOR UPDATE", [id]); if (!r.rows[0]) throw new Error("Revision unavailable."); const next = map(hydrate<T>(r.rows[0])); await tx.query("UPDATE content_revisions SET lifecycle=$2, body_hash=$3, updated_at=now() WHERE revision_id=$1", [id,next.lifecycle,next.bodyHash]); return next; }); }
  public submitForReview<T>(id: ContentRevisionId) { return this.transition<T>(id, submitForReview); }
  public approve<T>(id: ContentRevisionId) { return this.transition<T>(id, approveRevision); }
  public async publish(id: ContentRevisionId): Promise<ContentRevision<ContentAggregate>> { const published = await this.transition<ContentAggregate>(id, value => { assertPublishableContent(value.body); return publishRevision(value); }); await this.client.transaction(async tx => { for (const node of published.body.microSkills) await tx.query("INSERT INTO published_micro_skills (micro_skill_id,revision_id) VALUES ($1,$2) ON CONFLICT (micro_skill_id) DO UPDATE SET revision_id=EXCLUDED.revision_id,published_at=now()", [node.microSkill.id, id]); }); return published; }
  public async listPublishedHierarchy(): Promise<readonly ContentRevision<ContentAggregate>[]> { const result=await this.client.query<Row>("SELECT revision_id,lifecycle,body,body_hash FROM content_revisions WHERE lifecycle='PUBLISHED' ORDER BY revision_id"); return Object.freeze(result.rows.map(row=>hydrate<ContentAggregate>(row))); }
  public async selectInitialPublishedPair(actorId: ActorId, revisionId: ContentRevisionId): Promise<ReviewedPairChoice> { const revision=await this.getRevision<ContentAggregate>(revisionId); if (!revision || revision.lifecycle !== "PUBLISHED") throw new Error("CONTENT_INTEGRITY_FAILED"); const node=revision.body.microSkills.find(x=>x.microSkill.revisionId===revisionId); if (!node) throw new Error("CONTENT_INTEGRITY_FAILED"); return selectInitialPair({actorId,microSkillRevisionId:revisionId,eligiblePairs:node.pairs}); }
  public async selectFreshIndependentPair(actorId: ActorId, revisionId: ContentRevisionId, ordinal: number, exposedPairs: readonly {pairId:TaskPairId;pairVersion:string}[], exposedTasks: readonly {taskId:TaskId;version:string}[]) { const revision=await this.getRevision<ContentAggregate>(revisionId); if(!revision || revision.lifecycle!=="PUBLISHED") throw new Error("CONTENT_INTEGRITY_FAILED"); const node=revision.body.microSkills.find(x=>x.microSkill.revisionId===revisionId); if(!node) throw new Error("CONTENT_INTEGRITY_FAILED"); return selectFreshTransferPair({actorId,microSkillRevisionId:revisionId,independentAttemptOrdinal:ordinal,eligiblePairs:node.pairs,exposedPairs,exposedTransferTasks:exposedTasks}); }
  public deprecate<T>(id: ContentRevisionId) { return this.transition<T>(id, deprecateRevision); }
  public async editDraft<T>(id: ContentRevisionId, body: T): Promise<ContentRevision<T>> { return this.client.transaction(async tx => { const r=await tx.query<Row>("SELECT revision_id,lifecycle,body,body_hash FROM content_revisions WHERE revision_id=$1 FOR UPDATE",[id]); if(!r.rows[0]) throw new Error("Revision unavailable."); const next=editRevision(hydrate<T>(r.rows[0]),body); await tx.query("UPDATE content_revisions SET body=$2::jsonb,body_hash=$3,updated_at=now() WHERE revision_id=$1",[id,JSON.stringify(next.body),next.bodyHash]); return next; }); }
}
