import type { ContentRevisionId, MicroSkillId, SubjectId, TopicId } from "../domain/ids.js";
import type { ReviewedPairChoice } from "./selection.js";
import type { AnswerSpec, RichContent } from "./schema.js";
import { validateReviewedAssessment } from "./rubric.js";
export interface AuthoredTaskContent { readonly id: string; readonly version: string; readonly role: "practice" | "transfer"; readonly prompt: RichContent; readonly answerSpec: AnswerSpec; }
export interface AuthoredConnectionReveal { readonly id: string; readonly version: string; readonly pairId: string; readonly pairVersion: string; readonly title: string; readonly sharedRelation: string; readonly explanation: RichContent; }
export interface AuthoredReviewedPair extends ReviewedPairChoice { readonly practiceContent: AuthoredTaskContent; readonly transferContent: AuthoredTaskContent; readonly connectionReveal: AuthoredConnectionReveal; }
export interface MicroSkillAggregate { readonly subject: { readonly id: SubjectId; readonly displayOrder: number }; readonly topic: { readonly id: TopicId; readonly subjectId: SubjectId; readonly displayOrder: number }; readonly microSkill: { readonly id: MicroSkillId; readonly topicId: TopicId; readonly revisionId: ContentRevisionId; readonly displayOrder: number; readonly prerequisiteMicroSkillIds: readonly MicroSkillId[]; readonly nextMicroSkillId?: MicroSkillId }; readonly pairs: readonly AuthoredReviewedPair[]; }
export interface AggregateIssue { readonly code: string; readonly message: string; }
export interface ContentAggregate { readonly microSkills: readonly MicroSkillAggregate[]; }
export function validateContentAggregate(value: unknown): readonly AggregateIssue[] {
  if (!value || typeof value !== "object" || !Array.isArray((value as { microSkills?: unknown }).microSkills)) return [{ code: "MALFORMED_CONTENT_AGGREGATE", message: "Authored aggregate must contain microSkills." }];
  const aggregate = value as ContentAggregate;
  if (aggregate.microSkills.some((node) => !node || typeof node !== "object" || !node.microSkill || typeof node.microSkill !== "object" || !node.topic || typeof node.topic !== "object" || !node.subject || typeof node.subject !== "object" || !Array.isArray(node.pairs) || !Array.isArray(node.microSkill.prerequisiteMicroSkillIds) || typeof node.microSkill.id !== "string" || typeof node.microSkill.revisionId !== "string" || typeof node.microSkill.topicId !== "string")) return [{ code: "MALFORMED_CONTENT_AGGREGATE", message: "Micro-skill nodes are malformed." }];
  const issues: AggregateIssue[] = []; const nodes = new Map(aggregate.microSkills.map((node) => [node.microSkill.id, node]));
  if (nodes.size !== aggregate.microSkills.length) issues.push({ code: "DUPLICATE_MICROSKILL_ID", message: "Micro-skill identities must be unique." });
  if (new Set(aggregate.microSkills.map((node) => node.microSkill.revisionId)).size !== aggregate.microSkills.length) issues.push({ code: "DUPLICATE_CONTENT_REVISION_ID", message: "Content revision identities must be unique." });
  for (const node of aggregate.microSkills) {
    const { nextMicroSkillId: _next, ...identity } = node.microSkill; issues.push(...validateMicroSkillAggregate({ ...node, microSkill: { ...identity, prerequisiteMicroSkillIds: [] } }));
    if (new Set(node.microSkill.prerequisiteMicroSkillIds).size !== node.microSkill.prerequisiteMicroSkillIds.length) issues.push({ code: "DUPLICATE_PREREQUISITE", message: "Prerequisites must be unique." }); for (const prerequisite of node.microSkill.prerequisiteMicroSkillIds) { const target = nodes.get(prerequisite); if (!target) issues.push({ code: "UNKNOWN_PREREQUISITE", message: "Prerequisite must be in the authored aggregate." }); else if (target.microSkill.topicId !== node.microSkill.topicId || target.topic.subjectId !== node.topic.subjectId) issues.push({ code: "CROSS_SCOPE_PROGRESSION", message: "Progression must remain within one Topic." }); if (prerequisite === node.microSkill.id) issues.push({ code: "SELF_PREREQUISITE", message: "A micro-skill cannot require itself." }); }
    if (node.microSkill.nextMicroSkillId) { const target = nodes.get(node.microSkill.nextMicroSkillId); if (!target) issues.push({ code: "UNKNOWN_NEXT_RELATION", message: "Next relation must be in the authored aggregate." }); else if (target.microSkill.topicId !== node.microSkill.topicId || target.topic.subjectId !== node.topic.subjectId) issues.push({ code: "CROSS_SCOPE_PROGRESSION", message: "Progression must remain within one Topic." }); }
  }
  const forward = new Map<MicroSkillId, MicroSkillId[]>(); for (const id of nodes.keys()) forward.set(id, []); for (const node of aggregate.microSkills) { for (const prerequisite of node.microSkill.prerequisiteMicroSkillIds) forward.get(prerequisite)?.push(node.microSkill.id); if (node.microSkill.nextMicroSkillId) forward.get(node.microSkill.id)?.push(node.microSkill.nextMicroSkillId); } const visiting = new Set<MicroSkillId>(); const visited = new Set<MicroSkillId>(); const visit = (id: MicroSkillId): void => { if (visiting.has(id)) { issues.push({ code: "PROGRESSION_CYCLE", message: "Authored progression cannot cycle." }); return; } if (visited.has(id)) return; visiting.add(id); for (const edge of forward.get(id) ?? []) if (nodes.has(edge)) visit(edge); visiting.delete(id); visited.add(id); }; for (const id of nodes.keys()) visit(id); return issues;
}
export function validateMicroSkillAggregate(value: unknown): readonly AggregateIssue[] { try { if (!value || typeof value !== "object") return [{ code: "MALFORMED_MICROSKILL", message: "Micro-skill aggregate must be an object." }]; const raw = value as Partial<MicroSkillAggregate>; if (!raw.subject || !raw.topic || !raw.microSkill || !Array.isArray(raw.pairs)) return [{ code: "MALFORMED_MICROSKILL", message: "Micro-skill aggregate is incomplete." }]; const issues: AggregateIssue[] = []; const skill = raw.microSkill; if (typeof skill.id !== "string" || typeof skill.revisionId !== "string" || !Array.isArray(skill.prerequisiteMicroSkillIds)) return [{ code: "MALFORMED_MICROSKILL", message: "Micro-skill identity is malformed." }]; for (const pair of raw.pairs) { if (!pair || typeof pair !== "object") { issues.push({ code: "INVALID_PAIR_BANK_RELATION", message: "Pair must be an object." }); continue; } const p = pair as AuthoredReviewedPair; const task = (x: unknown, role: string) => { if (!x || typeof x !== "object") return false; const task = x as AuthoredTaskContent; if (task.role !== role || typeof task.id !== "string" || typeof task.version !== "string" || !task.prompt?.body || !task.answerSpec) return false; return task.answerSpec.kind !== "written_solution" || validateReviewedAssessment(task.answerSpec.assessment).length === 0; }; if (!task(p.practiceContent, "practice") || !task(p.transferContent, "transfer") || !p.connectionReveal || typeof p.connectionReveal !== "object") issues.push({ code: "INVALID_PAIR_BANK_RELATION", message: "Pair contains malformed reviewed content." }); } return issues; } catch { return [{ code: "MALFORMED_MICROSKILL", message: "Micro-skill aggregate is malformed." }]; } }
